# Generated by Django 5.1.2 on 2024-10-27 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('micr_code', models.CharField(blank=True, max_length=20, null=True)),
                ('login_id', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('FD', 'Fixed Deposit'), ('RD', 'Recurring Deposit'), ('DEMAT', 'Demat'), ('TRADING', 'Trading'), ('NRI', 'NRI'), ('LOAN', 'Loan'), ('CREDIT CARD', 'Credit Card'), ('MUTUAL FUND', 'Mutual Fund'), ('INSURANCE', 'Insurance'), ('PENSION', 'Pension'), ('FOREX', 'Forex'), ('OTHERS', 'Others')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Dormant', 'Dormant')], default='Active', max_length=20)),
                ('opening_date', models.DateField(blank=True, default=None, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amc', models.CharField(max_length=50)),
                ('fund_name', models.CharField(max_length=100)),
                ('isin', models.CharField(max_length=20)),
                ('scheme_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=20, unique=True)),
                ('stock_symbol', models.CharField(max_length=50)),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(max_length=50)),
                ('units', models.DecimalField(decimal_places=4, max_digits=9)),
                ('invested_amount', models.FloatField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.account')),
                ('fund_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.mutualfund')),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.DecimalField(decimal_places=4, max_digits=9)),
                ('nav_date', models.DateField()),
                ('fund_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.mutualfund')),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundTradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=50)),
                ('trade_date', models.DateField()),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('BONUS', 'Bonus'), ('SPLIT', 'Split'), ('MERGER', 'Merger'), ('OTHERS', 'Others')], max_length=10)),
                ('trade_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.DecimalField(decimal_places=4, max_digits=9)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.account')),
                ('fund_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.mutualfund')),
            ],
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatity', models.IntegerField()),
                ('stock_exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=10)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.account')),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockTradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=50)),
                ('trade_date', models.DateField()),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('BONUS', 'Bonus'), ('SPLIT', 'Split'), ('MERGER', 'Merger'), ('OTHERS', 'Others')], max_length=10)),
                ('stock_exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=10)),
                ('quatity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('trade_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.account')),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('trx_date', models.DateField()),
                ('trx_description', models.CharField(max_length=200)),
                ('trx_type', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=10)),
                ('trx_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trx_remarks', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labh.account')),
                ('cat_lev_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labh.catlevel1')),
                ('cat_lev_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labh.catlevel2')),
                ('cat_lev_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labh.catlevel3')),
            ],
        ),
    ]
